---
# tasks file for wordpress
#Baixar Wordpress e copia para /tmp
- name: Baixa o WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  become: yes

#Atualiza as configurações do apache para apontar para o wordpress e reinicia o apache
- name: Update default Apache site
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: present
    regexp: '(.)+DocumentRoot /var/www/html'
    line: 'DocumentRoot /var/www/wordpress'

- name: Restart Apache
  service:
    name: apache2
    state: restarted
 
#Descompacta o wordpress baixado anteriormente
- name: Descompacta o WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

#Renomeia o arquivo de exemplo para utilizar como arquivo padrão
- name: Renomeia o arquivos de comfiguração de exemplo 
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  become: yes

#Altera o arquivo wp-config.php e coloca os dados do banco de dados
- name: Configura wp-config.php
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{wp_mysql_db}}' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{wp_mysql_user}}' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{wp_mysql_password}}' );"}
    - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', '{{wp_mysql_host}}' );"}
  become: yes
