---
# tasks file for server
  - name: Atualiza o cache apt do servidor
    apt: update_cache=yes cache_valid_time=3600
    become: yes

  - name: Instala os pacotes necessarios  PHP
    apt:
      name: ['apache2','php-mysql','php','libapache2-mod-php','python3-mysqldb']
    become: yes